# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: pedro.urbina
email: pedro.urbina@gmail.com
description: A collection of ideas and projects by Pedro
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://pedrourbina.com" # the base hostname & protocol for your site
twitter_username: peddrrrooooo
github_username: terraflux

# Build settings
markdown: kramdown